---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/minio-cleaner
    tag: "latest"

inputs:
- name: minio-cleaner-git-repo

run:
  path: minio-cleaner-git-repo/ci/scripts/delete-old-artifacts.sh

params:
  host:
  access-key:
  secret-key:
  prefix:
  use-ssl:
  dry-run:
  bucket:
  backups-to-keep:
