---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/minio-cleaner
    tag: "latest"

inputs:
- name: minio-cleaner-git-repo

run:
  path: minio-cleaner-git-repo/ci/tasks/delete-old-artifacts.sh

params:
  host:
  access_key:
  secret_key:
  prefix:
  use_ssl:
  dry_run:
  bucket:
  backups_to_keep:
