resources:
- name: minio-cleaner-git-repo
  type: git
  source:
    uri: https://github.com/bbyers-pivotal/minio-cleaner.git
    branch: master

jobs:
- name: clean-up-minio
  plan:
  - get: minio-cleaner-git-repo
#    passed: [bbr-backup]
    trigger: true
  - task: delete-old-artifacts
    file: minio-cleaner-git-repo/ci/tasks/delete-old-artifacts.yml
    params:
      host: ((minio-host))
      access_key: ((minio-access-key))
      secret_key: ((minio-secret-key))
      prefix: ((minio-backup-prefix))
      use_ssl: ((use-ssl))
      dry_run: ((dry-run))
      bucket: ((minio-bucket))
      backups_to_keep: ((backups-to-keep))