jobs:
- name: clean-up-minio
  plan:
  - get: git-repo
    passed: [bbr-backup]
    trigger: true
  - task: delete-old-artifacts
    file: git-repo/ci/tasks/delete-old-artifacts.yml
    params:
      host: ((minio-host))
      access-key: ((minio-access-key))
      secret-key: ((minio-secret-key))
      prefix: ((minio-backup-prefix))
      use-ssl: true
      dry-run: true
      bucket: ((minio-bucket))
      backups-to-keep: ((backups-to-keep))